
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightORrightANDnonassocDIFERENTEIGUALIGUALMENORIGUALMAYORIGUALMENORMAYORleftMASMENOSleftPORDIVMODULOrightPOTENCIArightNOTAND BREAK CADENA CARACTER CHAR COMA CONTINUE CORDER CORIZQ COS DECIMAL DIFERENTE DIV DOLAR DOSPUNTOS DOSPUNTOSDOSPUNTOS ELSE ELSEIF END ENTERO FALSE FLOAT FLOAT64 FOR FUNCTION GLOBAL ID IF IGUAL IGUALIGUAL IN INT64 LOCAL LOG LOG10 LOWERCASE MAS MAYOR MAYORIGUAL MENOR MENORIGUAL MENOS MODULO MUTABLE NOT NULO OR PARDER PARIZQ PARSE POR POTENCIA PRINT PRINTLN PUNTO PUNTOYCOMA RETURN SIN SQRT STRING STRUCT TAN TRUE TRUNC TYPEOF UPPERCASE WHILEINICIO : STRING'
    
_lr_action_items = {'STRING':([0,],[2,]),'$end':([1,2,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'INICIO':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> INICIO","S'",1,None,None,None),
  ('INICIO -> STRING','INICIO',1,'p_init','grammar.py',200),
]
