
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftIGIGDIFDEnonassocMENMAYleftMASMENOSleftPORDIVrightUMENOSleftPARIZQPARDERAND DECIMAL DIFDE DIV ENTERO IGIG MAS MAY MEN MENOS OR PARDER PARIZQ POR RFALSE RTRUEl  :     l   OR  ml  :   mm  :   m   AND rm  :   rr  :   e   MAY er  :   e   MEN er  :   e   IGIG er  :   e   DIFDE er  :   RTRUEr  :   RFALSEr  :   ee  :     e   MAS     e\n            |   e   MENOS   e\n            |   e   POR     e\n            |   e   DIV     e e  :     MENOS   e   %prec   UMENOSe : PARIZQ e PARDERe    : ENTERO\n            | DECIMAL'
    
_lr_action_items = {'RTRUE':([0,11,12,],[5,5,5,]),'RFALSE':([0,11,12,],[6,6,6,]),'MENOS':([0,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,25,26,27,28,29,30,31,32,33,],[7,18,7,7,-18,-19,7,7,7,7,7,7,7,7,7,7,-16,18,18,18,18,18,-12,-13,-14,-15,-17,]),'PARIZQ':([0,7,8,11,12,13,14,15,16,17,18,19,20,],[8,8,8,8,8,8,8,8,8,8,8,8,8,]),'ENTERO':([0,7,8,11,12,13,14,15,16,17,18,19,20,],[9,9,9,9,9,9,9,9,9,9,9,9,9,]),'DECIMAL':([0,7,8,11,12,13,14,15,16,17,18,19,20,],[10,10,10,10,10,10,10,10,10,10,10,10,10,]),'$end':([1,2,3,4,5,6,9,10,21,23,24,25,26,27,28,29,30,31,32,33,],[0,-2,-4,-11,-9,-10,-18,-19,-16,-1,-3,-5,-6,-7,-8,-12,-13,-14,-15,-17,]),'OR':([1,2,3,4,5,6,9,10,21,23,24,25,26,27,28,29,30,31,32,33,],[11,-2,-4,-11,-9,-10,-18,-19,-16,-1,-3,-5,-6,-7,-8,-12,-13,-14,-15,-17,]),'AND':([2,3,4,5,6,9,10,21,23,24,25,26,27,28,29,30,31,32,33,],[12,-4,-11,-9,-10,-18,-19,-16,12,-3,-5,-6,-7,-8,-12,-13,-14,-15,-17,]),'MAY':([4,9,10,21,29,30,31,32,33,],[13,-18,-19,-16,-12,-13,-14,-15,-17,]),'MEN':([4,9,10,21,29,30,31,32,33,],[14,-18,-19,-16,-12,-13,-14,-15,-17,]),'IGIG':([4,9,10,21,29,30,31,32,33,],[15,-18,-19,-16,-12,-13,-14,-15,-17,]),'DIFDE':([4,9,10,21,29,30,31,32,33,],[16,-18,-19,-16,-12,-13,-14,-15,-17,]),'MAS':([4,9,10,21,22,25,26,27,28,29,30,31,32,33,],[17,-18,-19,-16,17,17,17,17,17,-12,-13,-14,-15,-17,]),'POR':([4,9,10,21,22,25,26,27,28,29,30,31,32,33,],[19,-18,-19,-16,19,19,19,19,19,19,19,-14,-15,-17,]),'DIV':([4,9,10,21,22,25,26,27,28,29,30,31,32,33,],[20,-18,-19,-16,20,20,20,20,20,20,20,-14,-15,-17,]),'PARDER':([9,10,21,22,29,30,31,32,33,],[-18,-19,-16,33,-12,-13,-14,-15,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'l':([0,],[1,]),'m':([0,11,],[2,23,]),'r':([0,11,12,],[3,3,24,]),'e':([0,7,8,11,12,13,14,15,16,17,18,19,20,],[4,21,22,4,4,25,26,27,28,29,30,31,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> l","S'",1,None,None,None),
  ('l -> l OR m','l',3,'p_expresion_l_1','grammar.py',118),
  ('l -> m','l',1,'p_expresion_l_2','grammar.py',125),
  ('m -> m AND r','m',3,'p_expresion_m_1','grammar.py',130),
  ('m -> r','m',1,'p_expresion_m_2','grammar.py',137),
  ('r -> e MAY e','r',3,'p_expresion_r_1','grammar.py',142),
  ('r -> e MEN e','r',3,'p_expresion_r_2','grammar.py',150),
  ('r -> e IGIG e','r',3,'p_expresion_r_3','grammar.py',161),
  ('r -> e DIFDE e','r',3,'p_expresion_r_4','grammar.py',169),
  ('r -> RTRUE','r',1,'p_expresion_r_5','grammar.py',177),
  ('r -> RFALSE','r',1,'p_expresion_r_6','grammar.py',184),
  ('r -> e','r',1,'p_expresion_r_7','grammar.py',194),
  ('e -> e MAS e','e',3,'p_expresion_binaria','grammar.py',202),
  ('e -> e MENOS e','e',3,'p_expresion_binaria','grammar.py',203),
  ('e -> e POR e','e',3,'p_expresion_binaria','grammar.py',204),
  ('e -> e DIV e','e',3,'p_expresion_binaria','grammar.py',205),
  ('e -> MENOS e','e',2,'p_expresion_unaria','grammar.py',214),
  ('e -> PARIZQ e PARDER','e',3,'p_expresion_agrupacion','grammar.py',220),
  ('e -> ENTERO','e',1,'p_expresion_number','grammar.py',225),
  ('e -> DECIMAL','e',1,'p_expresion_number','grammar.py',226),
]
